#Range: 0.1 ~ 1024.0
cloudOverride = true
distance = 4.0
gpuIncompatibleMessageEnabled = true
irisSupport = true
is_enabled = true
shuffle = false
useIrisFBO = true
usePersistentBuffers = true
#Range: 0.0 ~ 100.0
celestialBodyHalo = false
windEffectFactor = 1.0
#Range: 0.0 ~ 10.0
randomPlacement = 0.0
#Range: 0.0 ~ 10.0
fuzziness = 1.0
#Range: 0.0 ~ 256.0
yRange = 64.0
#Range: -256.0 ~ 256.0
yOffset = 0.0
#Range: 0.0 ~ 100.0
sparsity = 0.0
#Range: 0.0 ~ 100.0
spacing = 5.25
#Range: 0.0 ~ 100.0
sizeXZ = 16.0
#Range: 0.0 ~ 10.0
sizeY = 8.0
#Range: 0.0 ~ 100.0
travelSpeed = 0.03
#Range: 0.0 ~ 100.0
colorVariationFactor = 1.0
#Range: 0.0 ~ 100.0
samplingScale = 1.0
#Range: 0.0 ~ 100.0
scaleFalloffMin = 0.25
#Range: 0.0 ~ 100.0
fadeEdge = 0.15
#Range: 1 ~ 1024
chunkSize = 32
#Range: 0 ~ 128
blackListedBiomes = [
  "ae2:spatial_storage",
  "aether_redux:cloudcaps",
  "aether_redux:frosted_forests",
  "aether_redux:gilded_grasslands",
  "aether_redux:gilded_groves",
  "aether_redux:glacial_tundra",
  "aether_redux:skyfields",
  "aether_redux:skyroot_shrublands",
  "aether_redux:the_blight",
  "aether:skyroot_forest",
  "aether:skyroot_grove",
  "aether:skyroot_meadow",
  "aether:skyroot_woodland",
  "bloodmagic:none",
  "deep_aether:aerglow_forest",
  "deep_aether:aerlavender_fields",
  "deep_aether:blue_aerglow_forest",
  "deep_aether:golden_grove",
  "deep_aether:golden_heights",
  "deep_aether:mystic_aerglow_forest",
  "deep_aether:yagroot_swamp",
  "minecraft:basalt_deltas",
  "minecraft:crimson_forest",
  "minecraft:end_barrens",
  "minecraft:end_highlands",
  "minecraft:end_midlands",
  "minecraft:nether_wastes",
  "minecraft:small_end_islands",
  "minecraft:soul_sand_valley",
  "minecraft:the_end",
  "minecraft:warped_forest",
  "outer_end:azure_forest",
  "outer_end:crystal_crag",
  "outer_end:primordial_pools",
  "regions_unexplored:blackstone_basin",
  "regions_unexplored:glistering_meadow",
  "regions_unexplored:infernal_holt",
  "regions_unexplored:mycotoxic_undergrowth",
  "regions_unexplored:redstone_abyss",
]
selectedPreset = 0
