
[light_sources]
	water_sensitive_check = true
	block_entities = true
	entities = true
	self = true

	[light_sources.settings]

		[light_sources.settings.entities]

			[light_sources.settings.entities.minecraft]
				chicken = true
				bee = true
				axolotl = true
				arrow = true
				trader_llama = true
				donkey = true
				cow = true
				fox = true
				pig = true
				slime = true
				pillager = true
				skeleton = true
				iron_golem = true
				bat = true
				frog = true
				rabbit = true
				zombie = true
				firework_rocket = true
				armor_stand = true
				sheep = true
				player = true
				item = true
				wolf = true
				villager = true
				salmon = true
				wandering_trader = true
				zombie_villager = true
				goat = true
				item_frame = true
				horse = true
				vindicator = true
				phantom = true
				painting = true
				cave_spider = true
				witch = true
				glow_squid = true
				cod = true
				glow_item_frame = true
				squid = true
				spider = true
				creeper = true
				enderman = true

			[light_sources.settings.entities.outer_end]
				stalker = true
				sinker = true

			[light_sources.settings.entities.handcrafted]
				fancy_painting = true

			[light_sources.settings.entities.endermanoverhaul]
				mushroom_fields_enderman = true
				end_enderman = true
				end_islands_enderman = true

			[light_sources.settings.entities.eidolon]
				wraith = true
				slimy_slug = true
				raven = true
				necromancer = true

			[light_sources.settings.entities.embers]
				ancient_golem = true

			[light_sources.settings.entities.creeperoverhaul]
				dripstone_creeper = true
				cave_creeper = true
				beach_creeper = true

			[light_sources.settings.entities.lootr]
				lootr_minecart = true

			[light_sources.settings.entities.labels]
				label = true

			[light_sources.settings.entities.naturalist]
				deer = true
				snail = true
				canary = true
				firefly = true
				bluejay = true
				snake = true
				coral_snake = true
				cardinal = true
				robin = true
				bass = true
				butterfly = true
				duck = true
				bear = true
				sparrow = true
				lizard_tail = true
				lizard = true
				finch = true

			[light_sources.settings.entities.bloodmagic]
				bloodlight = true

			[light_sources.settings.entities.create]
				super_glue = true
				crafting_blueprint = true

			[light_sources.settings.entities.ecologics]
				squirrel = true

			[light_sources.settings.entities.corpse]
				corpse = true

